"""Small sqlite3-compatible wrapper backed by Supabase PostgreSQL.

This lets the existing LearningXY application keep its cursor-based database
code while all records are stored in the persistent PostgreSQL database.
"""

import os
import re
from pathlib import Path

import psycopg


OperationalError = psycopg.Error


class Row:
    """A row supporting both row[0] and row["column"] like sqlite3.Row."""

    def __init__(self, columns, values):
        self._columns = tuple(columns)
        self._values = tuple(values)
        self._mapping = dict(zip(self._columns, self._values))

    def __getitem__(self, key):
        if isinstance(key, int) or isinstance(key, slice):
            return self._values[key]
        return self._mapping[key]

    def __iter__(self):
        return iter(self._values)

    def __len__(self):
        return len(self._values)

    def keys(self):
        return self._columns

    def __repr__(self):
        return repr(self._mapping)


def _row_factory(cursor):
    columns = (
        [column.name for column in cursor.description]
        if cursor.description
        else []
    )

    def make_row(values):
        return Row(columns, values)

    return make_row


def _translate_sql(sql):
    query = sql.strip()

    pragma = re.fullmatch(
        r"PRAGMA\s+table_info\(([^)]+)\)\s*;?",
        query,
        flags=re.IGNORECASE,
    )
    if pragma:
        table = pragma.group(1).strip().strip('"\'')
        return """
            SELECT ordinal_position - 1 AS cid, column_name AS name
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = %s
            ORDER BY ordinal_position
        """, (table,)

    if re.search(r"\bFROM\s+sqlite_master\b", query, re.IGNORECASE):
        literal = re.search(
            r"\bname\s*=\s*'([^']+)'", query, re.IGNORECASE
        )
        if literal:
            return """
                SELECT table_name AS name
                FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = %s
            """, (literal.group(1),)

    query = re.sub(
        r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        query,
        flags=re.IGNORECASE,
    )
    query = re.sub(
        r"INSERT\s+OR\s+IGNORE\s+INTO",
        "INSERT INTO",
        query,
        flags=re.IGNORECASE,
    )
    if re.match(r"INSERT\s+INTO\s+free_lessons\b", query, re.IGNORECASE):
        query = query.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"

    query = re.sub(
        r"ALTER\s+TABLE\s+(\w+)\s+ADD\s+COLUMN\s+(?!IF\s+NOT\s+EXISTS)",
        r"ALTER TABLE \1 ADD COLUMN IF NOT EXISTS ",
        query,
        flags=re.IGNORECASE,
    )
    query = query.replace("?", "%s")
    return query, None


class Cursor:
    def __init__(self, connection):
        self._connection = connection
        self._cursor = connection._connection.cursor(row_factory=_row_factory)
        self.lastrowid = None
        self._prefetched = []

    def execute(self, sql, parameters=()):
        translated, forced_parameters = _translate_sql(sql)
        parameters = forced_parameters if forced_parameters is not None else parameters
        normalized = " ".join(translated.lower().split())

        needs_id = normalized.startswith(
            "insert into teacher_applications"
        ) or normalized.startswith("insert into approved_teachers")

        if needs_id and " returning " not in normalized:
            translated = translated.rstrip().rstrip(";") + " RETURNING id"

        self._cursor.execute(translated, parameters or ())
        self._prefetched = []
        self.lastrowid = None

        if needs_id:
            row = self._cursor.fetchone()
            if row is not None:
                self.lastrowid = row[0]

        return self

    def fetchone(self):
        if self._prefetched:
            return self._prefetched.pop(0)
        return self._cursor.fetchone()

    def fetchall(self):
        rows = self._prefetched + list(self._cursor.fetchall())
        self._prefetched = []
        return rows

    def close(self):
        self._cursor.close()


class Connection:
    def __init__(self):
        database_url = os.getenv("DATABASE_URL")
        if not database_url:
            raise RuntimeError("DATABASE_URL is not configured.")
        self._connection = psycopg.connect(
            database_url,
            row_factory=_row_factory,
            connect_timeout=15,
        )
        self.row_factory = Row

    def cursor(self):
        return Cursor(self)

    def execute(self, sql, parameters=()):
        return self.cursor().execute(sql, parameters)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


def connect(_legacy_filename=None):
    return Connection()


# The old application uses these files only as table-existence guards. Creating
# empty placeholders preserves those guards; no application data is stored in
# them after this module is enabled.
for _legacy_name in (
    "bookings.db",
    "teacher_applications.db",
    "approved_teachers.db",
):
    Path(_legacy_name).touch(exist_ok=True)
